### ISSUE TITLE
Role assignment from ZMI is broken

### ISSUE THREAD

**Issue by valipod** [zopefoundation/Products.PluggableAuthService#61] opened 2019-12-18 16:10 UTC
*How to replicate:*
navigate to /acl_users/source_groups/manage_groups, click on a group (ex. _Administrators_) and on "Assign", search for a user.
*Result:*
The response contains incorrect information about the group - the group id is now
<pre>"['Administrators', 'Administrators']"</pre>
Any subsequent search will double this string. A try to assign the user results in a *BadRequest* crash.

**Comment by dataflake** [comment] 2019-12-18 16:52
Duplicate of #43 #51 #54 #56 and fixed in release version 2.1

**Closed as completed by dataflake** 2019-12-18 16:52 UTC
Labels: duplicate

**Comment by valipod** [comment] 2019-12-19 11:39
Sorry, I forgot to mention we have the problem on version 2.1.1. I also don't see anything about this in the changelog. Could you check, and maybe re-open the ticket?

**Comment by dataflake** [comment] 2019-12-20 08:34
I checked on the latest released version and cannot reproduce the issue.

I go to a ZODB group manager, and from the list of groups I click the question mark to go to the user assignment screen. From there I can search for and assign users without an issue.
