### ISSUE TITLE
Can not assign role to user

### ISSUE THREAD

**Issue by krissik** [zopefoundation/Products.PluggableAuthService#56] opened 2019-11-13 12:14 UTC
I hope here is the correct place for this.

If I try to assign a role to a user using portal_role_manager I get an error.

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module Products.PluggableAuthService.utils, line 4, in wrapper
  Module <string>, line 4, in manage_assignRoleToPrincipals
  Module AccessControl.requestmethod, line 88, in _curried
  Module Products.PluggableAuthService.plugins.ZODBRoleManager, line 421, in manage_assignRoleToPrincipals
  Module Products.PlonePAS.plugins.role, line 69, in assignRoleToPrincipal
  Module Products.PluggableAuthService.plugins.ZODBRoleManager, line 303, in assignRoleToPrincipal
TypeError: '<' not supported between instances of 'str' and 'list'

```

It is on my two plone 5.2.0 portals and on demo.plone.org so I don`t think that I have configured something wrong.

Maybe something went wrong after searching for a user to assign the role to. After that the role name is doubled in headline.
Before:
```
Assign Role: Reviewer (Properties)
```
After:
```
Assign Role: ['Reviewer', 'Reviewer'] (Properties)
```

**Comment by dataflake** [comment] 2019-11-13 13:26
Duplicate of #43 and #51 . Fix was released with version 2.1.

**Closed as completed by dataflake** 2019-11-13 13:26 UTC
Labels: duplicate
